import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  golangSidebar: [
    {
      type: 'category',
      label: 'Golang',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'golang' }],
    },
  ],

  dsaSidebar: [
    {
      type: 'category',
      label: 'DSA',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'dsa' }],
    },
  ],

  roadmapSidebar: [
    {
      type: 'category',
      label: 'Roadmap',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'roadmap' }],
    },
  ],
};

export default sidebars;