import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  nginxApiSidebar: [
    {
      type: 'category',
      label: 'NGINX',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'nginx' }],
    },
  ],
  reactjsApiSidebar: [
    {
      type: 'category',
      label: 'React JS',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'reactjs' }],
    },
  ],
  prismaApiSidebar: [
    {
      type: 'category',
      label: 'Prisma',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'prisma' }],
    },
  ],
  redisApiSidebar: [
    {
      type: 'category',
      label: 'Redis',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'redis' }],
    },
  ],
  restApiSidebar: [
    {
      type: 'category',
      label: 'REST API Design',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'rest-api-design' }],
    },
  ],
  gitSidebar: [
    {
      type: 'category',
      label: 'Git',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'git' }],
    },
  ],
  expressSidebar: [
    {
      type: 'category',
      label: 'ExpressJS',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'expressjs' }],
    },
  ],
  iotSidebar: [
    {
      type: 'category',
      label: 'IoT',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'iot' }],
    },
  ],
  nextjsSidebar: [
    {
      type: 'category',
      label: 'NextJS',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'nextjs' }],
    },
  ],
  researchPaperSidebar: [
    {
      type: 'category',
      label: 'Research Paper',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'research-paper' }],
    },
  ],
  mysqlSidebar: [
    {
      type: 'category',
      label: 'MySQL',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'mysql' }],
    },
  ],
  typescriptSidebar: [
    {
      type: 'category',
      label: 'TypeScript',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'typescript' }],
    },
  ],
  systemDesignSidebar: [
    {
      type: 'category',
      label: 'System Design',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'system-design' }],
    },
  ],
  higherStudiesSidebar: [
    {
      type: 'category',
      label: 'Higher Studies',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'higher-studies' }],
    },
  ],
  javascriptSidebar: [
    {
      type: 'category',
      label: 'Javascript',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'javascript' }],
    },
  ],
  designPatternsSidebar: [
    {
      type: 'category',
      label: 'Design Patterns',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'design-patterns' }],
    },
  ],
  oopSidebar: [
    {
      type: 'category',
      label: 'OOP',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'oop' }],
    },
  ],
  dockerSidebar: [
    {
      type: 'category',
      label: 'Docker',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'docker' }],
    },
  ],

  golangSidebar: [
    {
      type: 'category',
      label: 'Golang',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'golang' }],
    },
  ],

  dsaSidebar: [
    {
      type: 'category',
      label: 'DSA',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'dsa' }],
    },
  ],

  roadmapSidebar: [
    {
      type: 'category',
      label: 'Roadmap',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'roadmap' }],
    },
  ],
};

export default sidebars;