import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  designPatternsSidebar: [
    {
      type: 'category',
      label: 'Design Patterns',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'design-patterns' }],
    },
  ],
  oopSidebar: [
    {
      type: 'category',
      label: 'OOP',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'oop' }],
    },
  ],
  dockerSidebar: [
    {
      type: 'category',
      label: 'Docker',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'docker' }],
    },
  ],

  golangSidebar: [
    {
      type: 'category',
      label: 'Golang',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'golang' }],
    },
  ],

  dsaSidebar: [
    {
      type: 'category',
      label: 'DSA',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'dsa' }],
    },
  ],

  roadmapSidebar: [
    {
      type: 'category',
      label: 'Roadmap',
      collapsible: false,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'roadmap' }],
    },
  ],
};

export default sidebars;